# Generated by Django 2.2.4 on 2019-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('batch_name', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=5)),
                ('sch_name_10th', models.CharField(max_length=30)),
                ('sch_name_12th', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=10)),
                ('topper', models.BooleanField()),
                ('stu_about', models.CharField(max_length=400)),
                ('contact', models.EmailField(max_length=40)),
            ],
        ),
    ]
