# Generated by Django 2.2.4 on 2019-09-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='batch_name',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sch_name_10th',
            new_name='higher_edu',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='sch_name_12th',
            new_name='secondary_edu',
        ),
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(default='', max_length=5),
        ),
    ]
