# Generated by Django 2.2.4 on 2019-09-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0002_auto_20190908_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='', upload_to='brcm/images'),
        ),
    ]
