# Generated by Django 2.2.4 on 2019-09-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0003_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=40)),
                ('auth_name', models.CharField(max_length=50)),
                ('year_of_pub', models.IntegerField()),
                ('no_of_books', models.IntegerField()),
                ('books_issued', models.IntegerField()),
                ('issue_by', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=5)),
                ('image', models.ImageField(default='', upload_to='brcm/images')),
            ],
        ),
    ]
