# Generated by Django 2.2.4 on 2019-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0004_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('lab_id', models.AutoField(primary_key=True, serialize=False)),
                ('lab_name', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=2)),
                ('floor', models.CharField(choices=[('0', 'Ground'), ('1', 'First'), ('2', 'Second')], max_length=1)),
                ('room_no', models.IntegerField()),
            ],
        ),
    ]
