# Generated by Django 2.2.4 on 2019-09-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0005_lab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('Qualification', models.CharField(max_length=30)),
                ('Specialization', models.CharField(max_length=30)),
                ('Branch', models.CharField(max_length=30)),
                ('Experience', models.CharField(max_length=30)),
                ('Email_ID', models.CharField(max_length=40)),
                ('Research_Publications', models.IntegerField()),
                ('image', models.ImageField(default='', upload_to='brcm/images')),
            ],
        ),
        migrations.AlterField(
            model_name='lab',
            name='room_no',
            field=models.CharField(max_length=10),
        ),
    ]
