# Generated by Django 2.2.4 on 2019-09-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0006_auto_20190912_2253'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Faculty',
        ),
    ]
