# Generated by Django 2.2.4 on 2019-09-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brcm', '0007_auto_20190912_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='Qualification',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='Specialization',
            field=models.CharField(max_length=50),
        ),
    ]
